### ISSUE TITLE
Stops and immediately leaves Wilmot

### ISSUE THREAD

**Issue by Cathal-Brugha** [Erabior/RouteManager#41] opened 2023-12-30 22:33 UTC
Train stops them immediately leaves Wilmot, no time for passengers to get off or on. Usually happens when train is backing up from Sylva/Dillsboro. Wilmot passengers get kicked off at Whittier when it stops there.

**Comment by AdamC1228** [comment] 2023-12-30 23:04
As always please provide at least the player.log file for review and if possible the steps to reproduce.

**Comment by Cathal-Brugha** [comment] 2023-12-30 23:21
[Player.log](https://github.com/Erabior/RouteManager/files/13799401/Player.log)

Train started between Wilmot and Dilsboro (where it was when save loaded). Stations checked for route, Dillsboro, Sylva ( to make train head in correct direction). At Sylva all stations were checked in route so train would stop at all stations. When finished at Sylva, train proceeded backwards to Dillsboro, unloaded and loaded passengers properly. At Wilmot train stopped then immediately left. At whittier train stopped, unloaded and loaded properly, and kicked off all Wilmot passengers that were not unloaded at Wilmot previously.

**Comment by AdamC1228** [comment] 2023-12-30 23:31
I see that you are using release 1.0.1.12. Please retest using the latest version (1.0.1.13) which addresses some passenger loading concerns and stations stopping behavior.

**Comment by Erabior** [comment] 2023-12-31 03:02
marking as duplicate of #36

**Closed as completed by Erabior** 2023-12-31 03:02 UTC
