### ISSUE TITLE
V2.0.0.6 "Holding at [Station] due to low fuel" causing issues.

### ISSUE THREAD

**Issue by Kaceyproductions** [Erabior/RouteManager#91] opened 2024-01-17 08:49 UTC
Basically, the train gets stuck in really.. interesting places.

Had my train running along doing its thing, when it stopped in Ela and warned me of low fuel. It then refused to leave Ela for.. any reason. 

Only way I found to get it out was to turn on "pause for refueling," manually/old AI drive most of the way to Bryson, then reengage RM. 

Should definitely have something somewhere look to see if there is the needed fueling amenities (coal, water, or diesel) in whatever town you're stopped in.

Anyway, as I was typing this, the AI blew past Bryson. Will need to do a full restart of the AI, it seems.

**Comment by AdamC1228** [comment] 2024-01-17 20:15
Closing as duplicate of #89

**Closed as completed** 2024-01-17 20:15 UTC
Labels: duplicate
