### ISSUE TITLE
Alarka Junction AI pathfinding issues

### ISSUE THREAD

**Issue by NicholasRB** [Erabior/RouteManager#5] opened 2023-12-21 23:10 UTC
Alarka Junction seems to pose a problem for the pathing somehow in that the AI will attempt to find a place to stop at the station but continuously pass it. Then it will pull forward and try again and do this on repeat forever, never stopping in the right spot to load/unload.

**Comment by Erabior** [comment] 2023-12-21 23:24
the cause of this issue is the fact that i have only programmed the station that leads to Cochran and Alarka. The intended route is ... <-> Hemingway <-> Alarka Jct <-> Cochran <-> Alarka <-> Almond <-> ...

**Comment by NicholasRB** [comment] 2023-12-21 23:26
Thanks for getting back so fast. That makes perfect sense and is an easy workaround for now

**Comment by Erabior** [comment] 2023-12-21 23:29
yeah, as long as you stop at Cochran between Alarka Jct and Almond all should be golden. But you should be able to run a service that brings passengers going to all destinations from Alarka and Cochran to Alarka Jct so that the 'main line' service can bring them where they need to be. (assuming you can drop passengers at stations that are not their destination. Have not tried this yet)

**Comment by dtwilliams10** [comment] 2023-12-22 03:12
This sounds like the issue I was having at Alarka, but I'm coming from Whittier <-> Ela <-> Bryson <-> Can't remember the station <-> Alarka. AI seems to not be able to handle a turn around at Alarka to head in reverse down the station list.

**Comment by Erabior** [comment] 2023-12-22 04:34
I personally have not gotten to Alarka just yet so if you could potentially get a video of the issue that would be great. Also I know I have been pushing out versions like a machine gun but if you could upgrade to the [latest](https://github.com/Erabior/RouteManager/releases/latest) version to get that vid if you can, that would be fantastic

**Comment by dtwilliams10** [comment] 2023-12-23 14:47
I picked up the beta 1.0.1.5 and it appears that Alarka functionality has improved dramatically!

**Comment by Erabior** [comment] 2023-12-23 17:00
Fantastic, I'll close this issue as solved with [Beta 1.0.1.5](https://github.com/Erabior/RouteManager/releases/tag/1.0.1.5)

**Closed by Erabior** 2023-12-23 17:00 UTC
Labels: Known Issue, Fix Coming with Future Feature Release
