### ISSUE TITLE
Enhancement - Schedule, of sorts?

### ISSUE THREAD

**Issue by dodougla** [Erabior/RouteManager#70] opened 2024-01-06 22:24 UTC
This is an enhancement request:  Any chance we could ever specify a game clock time to depart each station?  Like if we set "17:07" for Natanhala it would not leave that station _before_ that time.  If it arrives on time or late, it would leave a soon as loading/unloading completes.

Advanced level would be being able to save and load these "schedules" as config files for any given train.

This would be helpful for a SP game where I need to maintain some sort of schedule so meets can be arranged, etc.

**Comment by AdamC1228** [comment] 2024-01-06 22:53
Sounds like a duplicate of #50. This might be visited in a future release but with the current state of the mod & game this is not something that will be implemented until we have sorted out an approach to an in-game interface not bound to the car inspector window and we are not focusing on UI design until after V2 releases

**Closed as not planned by AdamC1228** 2024-01-06 22:53 UTC
Labels: duplicate, Enhancement

**Comment by dodougla** [comment] 2024-01-06 23:54
Completely understandable. I had looked at 50 but went ahead and posted
another one, because I was mainly looking for something that involved the
game clock time. Also, I was less concerned with waiting a certain period
of time, but rather, ensuring that the train does not leave before the
scheduled time which is far more important when running a timetable.

Thanks for your work, and I am looking forward to what else comes in the
future.
