### ISSUE TITLE
Failing to await all passengers to unload

### ISSUE THREAD

**Issue by hjp766** [Erabior/RouteManager#25] opened 2023-12-27 20:41 UTC
Just found it departing stations before all pax offloaded. Log will include part of me manually backing up. Screenshot shows the car tooltip with the relevant pax.

![image](https://github.com/Erabior/RouteManager/assets/154560143/1c2b3e91-ec1b-4c5c-9b6e-898d924121d7)
[departing pre unload finish.txt](https://github.com/Erabior/RouteManager/files/13781475/departing.pre.unload.finish.txt)

**Comment by Erabior** [comment] 2023-12-28 18:47
i see the issue here. I was hoping this was not likely enough to happen but it did. Basically the current logic checks for a change in the number of passengers on the train every 10 seconds. The train will only depart if there are exactly the same number of passengers on the train 'now' as there were 10 seconds ago. This only happens if loading is done, or as in this case, the checks fire at just the right time and you get the same number because the passengers/second went from negative to positive between the checks. Fix for this will be implemented in the next release

**Comment by Erabior** [comment] 2023-12-30 21:53
this specific issue was fixed but a similar bug exists caused by a different edge case. Marking this specific issue as solved, but is essentially a duplicate of #36

**Closed by Erabior** 2023-12-30 21:53 UTC
Labels: Minor Bug
